<?php
$typeArr[1] = '在线留言';
$typeArr[2] = '圈子';
$typeArr[3] = '问答';
$typeArr[4] = '小说';
$typeArr[5] = '红娘服务';
$typeArr[6] = '婚恋课堂';
$typeArr[7] = '直营门店';
$typeArr[8] = '相亲活动';
$typeArr[9] = '关于我们';
$typeArr[10] = '微圈子';
$typeArr[11] = '金玉传媒';
$typeArr[12] = '媒体报道';
$typeArr[13] = '相亲日记';
$typeArr[14] = '恋爱宝典';
$typeArr[15] = '十二生肖';
$typeArr[16] = '星座匹配';
$typeArr[17] = '生活秘密';
$typeArr[18] = '恋爱经历';
$typeArr[19] = '成都天府广场旗舰店';
$typeArr[20] = '成都温哥华广场店';
$typeArr[21] = '绵阳万达广场店';
$typeArr[22] = '我想说';
$typeArr[23] = '缘来在这里';
$typeArr[24] = '站外推荐';
$typeArr[25] = '成功故事';
?>