<li>
                        <div class="hn_tx"><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" alt="[field:title/]" /></a></div>
                        
                        <div class="hn_fl">
                        <div class="hn_name"><a href="[field:arcurl/]" target="_blank">[field:title/]</a><i>[field:zhiwei/]</i><p>[field:linian function='cn_substr(@me,62)'/]...</p></div>
                        <div class="clear"></div>
                        <div class="hn_info">从业经验: <i>[field:jingyan /]</i><br />成功配对: <i>[field:anli/]</i></div>
                        <div class="clear"></div>
                        <div class="hn_zx"><a href="[field:arcurl/]" target="_blank" class="hn_zx1">详细资料</a><a href="/call.html" class="hn_zx2" target="_blank">求配对</a></div>
                        </div>
                    </li>