<?php
$z[0]=Array("arcurl","",87,102);
$z[1]=Array("litpic","",156,171);
$z[2]=Array("title","",178,192);
$z[3]=Array("zhuangtai","\r\n                        	\$zhuangtai=@me;\r\n                            if(\$zhuangtai=='已结束'){\r\n                            	@me='<span class=\"enterStop\">报名结束</span>';\r\n                            }else{\r\n                            	@me='<span class=\"enterNow\">正在报名</span>';\r\n                            }\r\n                        ",272,674);
$z[3][4]['runphp']="yes";
$z[4]=Array("arcurl","",753,768);
$z[5]=Array("title","",801,815);
$z[6]=Array("didian","",875,890);
$z[7]=Array("feiyong","",903,919);
$z[8]=Array("baoming","",932,948);
$z[9]=Array("zhuangtai","\r\n                        	\$zhuangtai=@me;\r\n                            if(\$zhuangtai=='已结束'){\r\n                            	@me='<i class=\"jiezhi\">活动截至</i>';\r\n                            }else{\r\n                            	@me='<i>立即报名</i>';\r\n                            }\r\n                        ",991,1361);
$z[9][4]['runphp']="yes";

?>