<div class="newslist_count">
                    	<h2><a href="[field:arcurl/]" target="_blank"><b>[[field:typename /]]</b> [field:title/]</a></h2>
                        <div class="clear"></div>
                        <ul>
                        	[field:id function=Getimgs(@me,3,'li')/]
                        </ul>
                        <div class="clear"></div>
                        <div class="news_info">[field:pubdate function="GetDateTimeMK(@me)"/]</div>
                    </div>