<li>
                    	<a href="">
                        	<div class="pic_box"><img src="http://wx2.sinaimg.cn/crop.35.0.569.427.120/005M94J9ly1felzw3fpi0j30hs0bv766.jpg" /></div>
                            <div class="info_box">
                            	<div class="ktj_title">镜头素质大战 华硕鹰眼3对比iPhone7</div>
                            	<div class="ktj_info">产品：鹰眼3（ZE553KL/全网通）华硕手机1华硕鹰眼3握感较好 整体做工细致      相信不少朋友对于拍照手机第一印象就是iPhone，其实不然，笔者在最近使用手机中发现，有这么一款手机在拍照上可以和iPhone 7一决高下，这就是笔者试用的华硕鹰眼3，年初的CES上面</div>
                            </div>
                        </a>
                    </li>