<div class="newslist_count">
                    	<h2><a href="[field:arcurl/]" target="_blank">[[field:typename /]][field:title/]</a></h2>
                        <div class="clear"></div>
                        <ul>
                        	[field:id function=Getimgs(@me,3,'li')/]
                        </ul>
                        <div class="clear"></div>
                        <div class="news_info">时间：[field:pubdate function="GetDateTimeMK(@me)"/] &nbsp;&nbsp; 阅读：[field:click/]</div>
                    </div>