<li>
            	<div class="con_vip_hidden">
                    <a href="/member/index.php?uid=[field:userid/]" target="_blank">
                        <div class="con_vip_img"><img src="[field:face/]" /></div>
                    </a>
                    <div class="con_vip_zx">
                        <a href="javascript:;" onclick="cdpopuptrigger2(-2,'[field:uname/]','[field:face/]')"><span class="s-hi"><i></i>发私信</span></a>
                        <b>|</b>
                        <a href="javascript:;"><span class="l-wu"><i></i>送礼物</span></a>
                    </div>
                </div>
                <div class="clear"></div>
                <div class="con_vip_name"><a href="/member/index.php?uid=[field:userid/]" target="_blank">[field:uname/]</a></div>
                <div class="clear"></div>
                <p>
                    <i>[field:birthday/]岁 | 178CM | [field:city/]</i>
                </p>
                <em title="点击对话" onclick="cdpopuptrigger2(-2,'[field:uname/]','[field:face/]')">对话</em>
            </li>