<li><div class="hn_list_img"><a href="javascript:;" onclick="cdpopuptrigger([field:id/])"><img src="[field:litpic/]" /><p class="hn_list_p"><b>[field:title/]</b><br />高级婚恋顾问/5年经验</p></a><a href="" class="hn_zxbtn" title="在线咨询红娘">咨询红娘</a></div>
                    <div class="cd-popup2 tanchu[field:id/]">
                        <div class="cd-popup-container2">
                            <div class="cd-buttons2">
                                <div class="tc_img">
                                    <img src="/images/hntx_11.jpg" /><br />
                                    <b>张老师</b><br /><span>高级婚恋顾问/5年经验</span>
                                    <div class="tc_zx"><a href="">查看详情</a><a href="" class="hover">在线咨询</a></div>
                                </div>
                                <div class="tc_text">
                                	<p>张老师是个言语犀利但内心善良的人，她痛快地指出你的不足，并给出建议，帮你提高爱与被爱的能力，成为一个更优秀的人，一个能吸引到更多优秀异性眼光的人。让你成功找到另一半。这是欧老师一直努力做的事情。</p>
                                    <p><b>服务理念</b>美满的婚姻是人生当中最重要的事情之一，因此我非常珍惜每一次和会员的交流，尊重并理解会员
的需要，把每一位会员当成自己的朋友对待，耐心地用自己的专业知识帮助会员找寻幸福。</p>
									<p><b>婚恋建议</b>用心把握每一个属于自己缘分，用心去经营，相信自已一定会找到属于自已的幸福！</p>
                                </div>
                            </div>
                            <a href="javascript:;" onclick="cdpopupclose([field:id/])" class="cd-popup-close2">close</a>
                        </div>
                    </div>
                    </li>