<li>
                <a href="/member/index.php?uid=[field:userid/]" target="_blank">
                    <div class="con_vip_img"><img src="[field:face/]" /></div>
                </a>
                <div class="con_vip_zx"><span class="s-hi"><i></i>发私信</span><span class="l-wu"><i></i>送礼物</span></div>
                <div class="clear"></div>
                <div class="con_vip_name"><a href="/member/index.php?uid=[field:userid/]" target="_blank">[field:uname/]</a></div>
                <div class="clear"></div>
                <p>
                    <i>[field:birthday function="birthday3(@me)"/]岁 | 178CM | 成都</i>
                </p>
                <em title="点击对话" onclick="cdpopuptrigger2(-2,'[field:uname/]','[field:face/]')">对话</em>
            </li>