<li>
                    	<div class="chuanmei_fr_img2"><a href="[field:arcurl/]"><img src="[field:litpic /]" alt="[field:title/]" /></a></div>
                        <div class="chuanmei_fr_title2"><a href="[field:arcurl/]">[field:title/]</a></div>
                    </li>
                	<li>
                    	<div class="chuanmei_fr_img2"><a href="[field:arcurl/]"><img src="[field:litpic /]" alt="[field:title/]" /></a></div>
                        <div class="chuanmei_fr_title2"><a href="[field:arcurl/]">[field:title/]</a></div>
                    </li>