<li>
                    	<a href="[field:arcurl/]">
                        	<div class="pic_box"><img src="[field:litpic /]" /></div>
                            <div class="info_box">
                            	<div class="ktj_title">[field:title/]</div>
                            	<div class="ktj_info">[field:description/]...</div>
                            </div>
                        </a>
                    </li>