
<field:shouji itemname="手机号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:shouji>

<field:xingming itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xingming>

<field:xingbie itemname="性别" autofield="1" type="radio" isnull="true" default="男,女"  maxlength="250" page="">
</field:xingbie>

<field:renshu itemname="人数" autofield="1" type="select" isnull="true" default="1,2,3,4,5,6,7,8,9,10"  maxlength="250" page="">
</field:renshu>
