<?php
$z[0]=Array("arcurl","",66,81);
$z[1]=Array("litpic","",93,109);
$z[2]=Array("title","",116,130);
$z[3]=Array("arcurl","",211,226);
$z[4]=Array("title","",228,242);
$z[5]=Array("info","",309,322);
$z[6]=Array("arcurl","",440,455);
$z[7]=Array("litpic","",467,483);
$z[8]=Array("title","",490,504);
$z[9]=Array("arcurl","",585,600);
$z[10]=Array("title","",602,616);
$z[11]=Array("info","",683,696);

?>