<li>
                    	<div class="kt_newright2_img"><a href="[field:arcurl/]"><img src="[field:litpic /]" alt="[field:title/]" /></a></div>
                        <div class="kt_newright2_title"><a href="[field:arcurl/]">[field:title/]</a></div>
                        <div class="kt_newright2_info">[field:info/]</div>
                    </li>
                	<li>
                    	<div class="kt_newright2_img"><a href="[field:arcurl/]"><img src="[field:litpic /]" alt="[field:title/]" /></a></div>
                        <div class="kt_newright2_title"><a href="[field:arcurl/]">[field:title/]</a></div>
                        <div class="kt_newright2_info">[field:info/]</div>
                    </li>