<field:jingyan itemname="从业经验" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jingyan>
<field:zhiwei itemname="职位称呼" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhiwei>
<field:haoping itemname="好评率" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:haoping>
<field:anli itemname="成功案例" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:anli>
<field:linian itemname="服务理念" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:linian>
<field:jieshao itemname="红娘介绍" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jieshao>

<field:gongsi itemname="所在公司" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="成都天府广场旗舰店,成都温哥华广场店,绵阳万达广场店"  maxlength="250" page="">
</field:gongsi>


