	
<field:onlynet itemname="联系方式限制" autofield="1" type="int" isnull="true" default="1"  maxlength="250" issearch="" isshow="" state="1">	
</field:onlynet>	
	
	
	
<field:uname itemname="显示昵称" autofield="1" type="textchar" isnull="" default=""  maxlength="30" issearch="0" isshow="0" state="0">
</field:uname>

	
	
<field:qq itemname="QQ" autofield="1" type="textchar" isnull="true" default=""  maxlength="12" issearch="" isshow="" state="0">
</field:qq>	
	
<field:msn itemname="MSN" autofield="1" type="textchar" isnull="true" default=""  maxlength="50" issearch="" isshow="" state="0">
</field:msn>	
	
<field:tel itemname="电话号码" autofield="1" type="text" isnull="true" default=""  maxlength="15" issearch="" isshow="" state="0">
</field:tel>	
	
<field:mobile itemname="手机号码" autofield="1" type="text" default=""  maxlength="15" issearch="0" isshow="0" state="1">
	
</field:mobile>
	
	
<field:place itemname="现居城市" autofield="1" type="int" isnull="" default="0"  maxlength="5" issearch="0" isshow="0" state="1">
</field:place>
	
	
	
<field:oldplace itemname="家乡地址" autofield="1" type="int" isnull="" default="0"  maxlength="5" issearch="0" isshow="0" state="0">
</field:oldplace>
	
	
	
<field:birthday itemname="年龄" autofield="1" type="int" default=""  maxlength="250" issearch="0" isshow="0" state="1">
	
</field:birthday>









	
	
<field:star itemname="星座" autofield="1" type="int" isnull="true" default="1"  maxlength="6" issearch="" isshow="" state="1">	
</field:star>	
	
<field:income itemname="收入范围" autofield="1" type="int" default="0"  maxlength="6" issearch="0" isshow="0" state="1">
	
</field:income>
	
	
<field:education itemname="学历范围" autofield="1" type="int" default="0"  maxlength="6" issearch="0" isshow="0" state="1">
	
</field:education>
	
	
<field:height itemname="身高" autofield="1" type="int" isnull="true" default="160"  maxlength="5" issearch="" isshow="" state="1">	
</field:height>	
	
<field:bodytype itemname="体重" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:bodytype>	
	
<field:blood itemname="血型" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:blood>	
	
<field:vocation itemname="职业" autofield="1" type="text" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:vocation>	
	
<field:smoke itemname="吸烟" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:smoke>	
	
<field:marital itemname="婚姻状况" autofield="1" type="text" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:marital>	
	
<field:house itemname="住房" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:house>	
	
<field:drink itemname="饮酒" autofield="1" type="int" isnull="true" default="0"  maxlength="6" issearch="" isshow="" state="1">	
</field:drink>	
	
<field:datingtype itemname="交友目的" autofield="1" type="int" default="0"  maxlength="6" issearch="0" isshow="0" state="1">
	
</field:datingtype>
	
	
<field:language itemname="语言" autofield="1" type="checkbox" isnull="true" default="普通话,上海话,广东话,英语,日语,韩语,法语,意大利语,德语,西班牙语,俄语,阿拉伯语"  maxlength="250" issearch="" isshow="" state="0">
</field:language>	
	
	
<field:nature itemname="性格" autofield="1" type="checkbox" isnull="true" default="性格外向,性格内向,活泼开朗,豪放不羁,患得患失,冲动,幽默,稳重,轻浮,沉默寡言,多愁善感,时喜时悲,附庸风雅,能说会道,坚强,脆弱,幼稚,成熟,快言快语,损人利己,狡猾善变,交际广泛,优柔寡断,自私,真诚,独立,依赖,难以琢磨,悲观消极,郁郁寡欢,胆小怕事,乐观向上,任性,自负,自卑,拜金,温柔体贴,小心翼翼,暴力倾向,逆来顺受,不拘小节,暴躁,倔强,豪爽,害羞,婆婆妈妈,敢做敢当,助人为乐,耿直,虚伪,孤僻,老实,守旧,敏感,迟钝,婆婆妈妈,武断,果断,刻薄"  maxlength="250" issearch="" isshow="" state="0">
</field:nature>	
	
<field:lovemsg itemname="人生格言" autofield="1" type="text" isnull="true" default=""  maxlength="100" issearch="" isshow="" state="1">	
</field:lovemsg>	
	
<field:address itemname="家庭住址" autofield="1" type="text" isnull="true" default=""  maxlength="50" issearch="" isshow="" state="0">
</field:address>	
	
<field:uptime itemname="更新时间" autofield="1" type="int" isnull="true" default=""  maxlength="10" issearch="" isshow="" state="0">
</field:uptime>	

<field:car itemname="购车情况" autofield="1" type="select" isnull="true" default="暂未购车,计划购车,已经购车"  maxlength="250" issearch="0" isshow="0" state="1">
</field:car>



<field:zinv itemname="有无子女" autofield="1" type="select" isnull="true" default="无子女,有儿子,有女儿,有儿女"  maxlength="250" issearch="0" isshow="0" state="1">
</field:zinv>

<field:duanlian itemname="锻炼习惯" autofield="1" type="select" isnull="true" default="健身达人,经常锻炼,偶尔锻炼,很少锻炼,从不锻炼"  maxlength="250" issearch="0" isshow="0" state="1">
</field:duanlian>

<field:zuoxi itemname="作息习惯" autofield="1" type="select" isnull="true" default="按时睡觉,经常熬夜,偶尔熬夜"  maxlength="250" issearch="0" isshow="0" state="1">
</field:zuoxi>

<field:zongjiao itemname="宗教信仰" autofield="1" type="select" isnull="true" default="无宗教信仰,有宗教信仰"  maxlength="250" issearch="0" isshow="0" state="1">
</field:zongjiao>

<field:zhiye itemname="职业职位" autofield="1" type="select" isnull="true" default="私营业主,国家单位,人力/行政/管理,计算机/通信/电子商务,财会/金融/保险,销售/客服/采购,法律/教育,医疗/制药/环保,生活/服务业"  maxlength="250" issearch="0" isshow="0" state="1">
</field:zhiye>

<field:hangye itemname="公司行业" autofield="1" type="select" isnull="true" default="食品饮料,服装行业,建筑开发,化工行业,纺织行业,造车行业,电脑行业,包装行业,运输行业,家电行业,电子行业,旅游行业,机械行业,化妆品行业,烟草行业,酿酒行业,互联网行业,中介行业,金属行业,广告行业,农业服务"  maxlength="250" issearch="0" isshow="0" state="1">
</field:hangye>

<field:waizhai itemname="外债贷款" autofield="1" type="checkbox" isnull="true" default="无外债贷款,房贷,车贷,留学贷款,助学贷款,个人生产经营性贷款"  maxlength="250" issearch="0" isshow="0" state="1">
</field:waizhai>

<field:jiawu itemname="家务" autofield="1" type="select" isnull="true" default="家务全部都我做,夫妻平均分配,谁有时间谁做,各自做擅长的"  maxlength="250" issearch="0" isshow="0" state="1">
</field:jiawu>

<field:chongwu itemname="宠物" autofield="1" type="select" isnull="true" default="没有养宠物,计划养宠物,有养小狗,有养猫咪,宠物达人"  maxlength="250" issearch="0" isshow="0" state="1">
</field:chongwu>

<field:yinshi itemname="饮食习惯" autofield="1" type="select" isnull="true" default="无特殊习惯,口味清淡,无辣不欢,口味偏重,无肉不欢,习惯吃素"  maxlength="250" issearch="0" isshow="0" state="1">
</field:yinshi>

<field:gouwu itemname="逛街购物" autofield="1" type="select" isnull="true" default="从来不去,没办法才去,偶尔逛逛,经常逛街,非常爱逛街,不逛就难受"  maxlength="250" issearch="0" isshow="0" state="1">
</field:gouwu>

<field:quanzi itemname="交际圈子" autofield="1" type="select" isnull="true" default="偶尔约会,经常约会,每月几次,很少约会,朋友很少"  maxlength="250" issearch="0" isshow="0" state="1">
</field:quanzi>

<field:xiaofei itemname="最大消费" autofield="1" type="select" isnull="true" default="享受美食,购置服装,购置包包,购置美鞋,美容护肤,健身锻炼,休闲娱乐,旅游度假,出行交通,电子产品,社交交友,电动游戏,其他"  maxlength="250" issearch="0" isshow="0" state="1">
</field:xiaofei>

<field:leixing itemname="工作状态" autofield="1" type="select" isnull="true" default="轻松稳定,朝九晚五,偶尔加班,经常加班,偶尔出差,经常出差,经常有应酬,时间自由"  maxlength="250" issearch="0" isshow="0" state="1">
</field:leixing>

<field:xiaohai itemname="是否要小孩" autofield="1" type="select" isnull="true" default="想要孩子,要不要都行,不要孩子,视情况而定"  maxlength="250" issearch="0" isshow="0" state="1">
</field:xiaohai>

<field:jiehun itemname="何时结婚" autofield="1" type="select" isnull="true" default="接受闪婚,顺其自然,一年内,两年内,三年以上"  maxlength="250" issearch="0" isshow="0" state="1">
</field:jiehun>

<field:yidilian itemname="异地恋" autofield="1" type="select" isnull="true" default="不能接受,能接受,视情况而定"  maxlength="250" issearch="0" isshow="0" state="1">
</field:yidilian>

<field:paihang itemname="家中排行" autofield="1" type="select" isnull="true" default="独生子女,老大,老二,老三,老四及更小"  maxlength="250" issearch="0" isshow="0" state="1">
</field:paihang>

<field:fumu itemname="父母情况" autofield="1" type="select" isnull="true" default="父母健在,单亲家庭,父亲健在,母亲健在,父母均离世"  maxlength="250" issearch="0" isshow="0" state="1">
</field:fumu>

<field:yundong itemname="喜欢的运动" autofield="1" type="checkbox" isnull="true" default="足球,篮球,排球,网球,羽毛球,乒乓球,壁球,保龄球,手球,橄榄球,棒球,高尔夫,健身,跑步,自行车,摩托车,汽车,舞蹈,体操,跆拳道,柔道,空手道,游泳,潜水,水上运动,航海,滑雪,拳击,钓鱼,瑜珈,武术,其它,不喜欢运动"  maxlength="250" issearch="0" isshow="0" state="1">
</field:yundong>

<field:food itemname="喜欢的食物" autofield="1" type="checkbox" isnull="true" default="中国菜,印度菜,泰国菜,法国菜,意大利菜,俄罗斯菜,日本菜,烧烤,健康食品,素食,快餐,甜点,其他,无特别爱好"  maxlength="250" issearch="0" isshow="0" state="1">
</field:food>

<field:book itemname="喜欢的书籍" autofield="1" type="checkbox" isnull="true" default="校园青春,文学,艺术与摄影,励志与成功,动漫与幽默,政治与军事,哲学与宗教,历史传记,运动健身,健康与养生,烹饪与饮食,旅游,投资理财,婚恋与家庭,期刊杂志,娱乐时尚,人文社科,自然科学,收藏与鉴赏,其他"  maxlength="250" issearch="0" isshow="0" state="1">
</field:book>

<field:diany itemname="喜欢的电影" autofield="1" type="checkbox" isnull="true" default="爱情,喜剧,动作冒险,古装武侠,科幻魔幻,悬疑推理,惊悚恐怖,动画,战争,音乐歌舞,纪录片,剧情,西部,历史传记,其他,什么都看"  maxlength="250" issearch="0" isshow="0" state="1">
</field:diany>

<field:xiuxian itemname="娱乐休闲" autofield="1" type="checkbox" isnull="true" default="饭店,商场,剧院,电影院,音乐会,迪斯科,网吧,温泉,图书馆/书店,咖啡厅,游乐场,卡拉OK,体育馆,逛街,家里,其它"  maxlength="250" issearch="0" isshow="0" state="1">
</field:xiuxian>

<field:aihao itemname="业余爱好" autofield="1" type="checkbox" isnull="true" default="网络,汽车,动物,摄影,影视,音乐,写作,购物,手工艺,园艺,舞蹈,展览,烹饪,读书,绘画,计算机,体育运动,旅游,电子游戏"  maxlength="250" issearch="0" isshow="0" state="1">
</field:aihao>

<field:lvyou itemname="旅游去处" autofield="1" type="checkbox" isnull="true" default="惬意海岛,名山古刹,繁华都市,风情名城,广袤森林,高原雪域,秀美山水,历史遗迹,江河大川,峻秀峡谷,小桥流水,其他选择"  maxlength="250" issearch="0" isshow="0" state="1">
</field:lvyou>




