<div class="hdong_list">
            	<div class="hdong_list_tit"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></div>
            	<div class="hdong_list_img"><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" alt="[field:title/]" /></a><p>已报名人数：[field:baoming/]人</p></div>
            	<div class="hdong_list_bm">活动已结束 <a href="[field:arcurl/]" target="_blank" class="bmjz">报名截止</a></div>
            </div>