<div class="newslist_count">
                    	<a href="[field:arcurl/]" target="_blank">
                        <h2><b>[[field:typename /]]</b> [field:title/]</h2>
                        <div class="clear"></div>
                        <ul>
                        	[field:id function=Getimgs(@me,3,'li')/]
                        </ul>
                        <div class="clear"></div>
                        <div class="news_info">[field:pubdate function="GetDateTimeMK(@me)"/]</div>
                        </a>
                    </div>