
<field:zhuban itemname="活动主办方" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhuban>

<field:didian itemname="活动地点" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:didian>

<field:shijian itemname="活动时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:shijian>

<field:lianxi itemname="联系方式" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:lianxi>

<field:feiyong itemname="费用说明" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:feiyong>
