<?php
$z[0]=Array("include","",527,564);
$z[0][4]['filename']="header.htm";
$z[1]=Array("arclist","\r\n                   <a href=\"[field:arcurl/]\" target=\"_blank\" title=\"点击播放\">\r\n                   <img src=\"[field:bigimg /]\" alt=\"[field:title/]\" />\r\n                   <div class=\"video_f1_left_2\">[field:title/] <span>[field:click/]次播放</span></div>\r\n                   <i class=\"icon-play7070\" ></i>\r\n                   </a>\r\n                   ",970,1450);
$z[1][4]['titlelen']="100";
$z[1][4]['row']="1";
$z[1][4]['orderby']="pubdate";
$z[1][4]['flag']="c";
$z[1][4]['typeid']="11";
$z[1][4]['addfields']="bigimg";
$z[1][4]['channelid']="1";
$z[2]=Array("arclist","\r\n                      <li><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic /]\" alt=\"[field:title/]\" /><div class=\"video_f1_left_4\">[field:title/]</div></a></li>\r\n                      ",1582,1869);
$z[2][4]['titlelen']="100";
$z[2][4]['row']="4";
$z[2][4]['noflag']="c";
$z[2][4]['orderby']="id";
$z[2][4]['typeid']="22";
$z[3]=Array("arclist","\r\n                    	<li class=\"video_f1_left_51\"><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic /]\" /><div class=\"video_f1_left_6\">[field:title/]</div></a></li>\r\n                        ",2233,2519);
$z[3][4]['titlelen']="100";
$z[3][4]['row']="4";
$z[3][4]['orderby']="pubdate";
$z[3][4]['typeid']="23";
$z[4]=Array("arclist","\r\n                	<li>\r\n                    	<div class=\"chuanmei_fr_img2\"><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic /]\" alt=\"[field:title/]\" /></a></div>\r\n                        <div class=\"chuanmei_fr_title2\"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></div>\r\n                    </li>\r\n                    ",2803,3254);
$z[4][4]['titlelen']="100";
$z[4][4]['row']="5";
$z[4][4]['orderby']="click";
$z[4][4]['typeid']="11";
$z[4][4]['subday']="15";
$z[4][4]['noflag']="c";
$z[5]=Array("arclist","\r\n            	<li><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic /]\" alt=\"[field:title/]\" /><div class=\"video_f3_left_31\">[field:title/]</div></a></li>\r\n                ",3715,3983);
$z[5][4]['titlelen']="100";
$z[5][4]['row']="10";
$z[5][4]['orderby']="pubdate";
$z[5][4]['typeid']="24";
$z[6]=Array("include","",4182,4219);
$z[6][4]['filename']="footer.htm";

?>