<?php
$z[0]=Array("face","\r\n                        	\$face1=@me;\r\n                        	if(\$face1 == ''){\r\n                            	@me='<img src=\"/member/templets/images/dfboy.png\" />';\r\n                            }else{\r\n                            	@me='<img src='.\$face1.' />'; \r\n                            }\r\n                        ",30,389);
$z[0][4]['runphp']="yes";
$z[1]=Array("userid","",446,461);
$z[2]=Array("userid","",595,610);
$z[3]=Array("uname","",636,650);
$z[4]=Array("shijian","",692,708);
$z[5]=Array("aid","",759,771);
$z[6]=Array("huodong","",800,816);

?>