<?php
$z[0]=Array("spaceurl","",24,42);
$z[1]=Array("face","",71,84);
$z[2]=Array("spaceurl","",144,162);
$z[3]=Array("uname","",181,195);
$z[4]=Array("spaceurl","",231,249);
$z[5]=Array("spaceurl","",318,336);
$z[6]=Array("spaceurl","",416,434);
$z[7]=Array("rankname","",503,521);
$z[8]=Array("jointime","",536,588);
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",603,656);
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>