<?php
$z[0]=Array("userid","",61,76);
$z[1]=Array("face","\r\n                        	\$face1=@me;\r\n                        	if(\$face1 == ''){\r\n                            	@me='<img src=\"/member/templets/images/dfboy.png\" />';\r\n                            }else{\r\n                            	@me='<img src='.\$face1.' />'; \r\n                            }\r\n                        ",143,502);
$z[1][4]['runphp']="yes";
$z[2]=Array("userid","",589,604);
$z[3]=Array("uname","",630,644);
$z[4]=Array("shijian","",686,702);
$z[5]=Array("aid","",753,765);
$z[6]=Array("huodong","",794,810);

?>