<?php
$z[0]=Array("array","\r\n\r\nif(@me['source']=='1')\r\n{\r\n@me = '\r\n<div class=\"newslist_count\">\r\n<h2><a href=\"'.@me[arcurl].'\">'.@me[title].'</a></h2>\r\n<div class=\"clear\"></div>\r\n<ul>\r\n<li><a href=\"\"><img src=\"http://photocdn.sohu.com/recom/20170315/128881326_450_300_0.png\"></a></li>\r\n<li><a href=\"\"><img src=\"http://photocdn.sohu.com/recom/20170315/128881326_450_300_2.jpeg\"></a></li>\r\n<li><a href=\"\"><img src=\"http://photocdn.sohu.com/recom/20170315/128881326_450_300_1.jpeg\"></a></li>\r\n</ul>\r\n<div class=\"clear\"></div>\r\n<div class=\"news_info\">时间：2017-03-15 &nbsp;&nbsp; 阅读：7859</div>\r\n</div>'; \r\n\r\n}else{\r\n\r\n@me=@me['title'];\r\n\r\n}\r\n\r\n",0,663);
$z[0][4]['runphp']="yes";

?>