
<field:zhuban itemname="活动主办方" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zhuban>

<field:didian itemname="活动地点" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:didian>

<field:shijian itemname="活动时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:shijian>

<field:lianxi itemname="联系方式" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:lianxi>

<field:feiyong itemname="费用说明" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:feiyong>

<field:baoming itemname="已经报名" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:baoming>

<field:shuoming itemname="活动说明" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:shuoming>

<field:liucheng itemname="活动流程" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:liucheng>

<field:yaoqiu itemname="报名要求" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:yaoqiu>

<field:fangshi itemname="报名方式" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fangshi>

<field:zhuangtai itemname="活动状态" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="报名中,已结束"  maxlength="250" page="">
</field:zhuangtai>
