<div class="item" id="brand-[field:global.autoindex/]">
                          <div class="lover_img">
                          <a href="[field:arcurl/]" target="_blank">
                          <img src="[field:litpic /]" alt="[field:title/]" style="min-height:205px; max-height:600px;" />
                          </div>
                          <div class="clear"></div>
                          <div class="lover_tx">
                              <a href="/member/index.php?uid=[field:writer /]"><img src="" width="35" /></a>
                          </div>
                          <div class="lover_title">[field:description/]</div>
                      </div><!--item-->