<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?>	<script type="text/javascript" src="/images/js/top.js"></script>

    <div id="top"></div>

    <div class="foot_reg">
    	<div class="foot_wd">
        	<div class="foot_h1">免费相亲 金玉良缘</div>
            <div class="foot_c">
            	<a href="/call.html" target="_blank" class="hover">在线咨询</a><a href="/member/">登陆</a><a href="/member/index_do.php?fmdo=user&dopost=regnew">注册</a>
            </div>
            <div class="clear"></div>
            <div class="foot_call">红娘热线：028-86145520</div>
        </div>
    </div>
    
    <div class="clear"></div>
    
    <div class="footer">
    	<div class="footer1">
            <a href="">联系客服</a>
            <a href="">关于我们</a>
            <a href="">网站地图</a>
            <a href="">联系我们</a>
            <a href="">注册条款</a>
            <a href="">友情链接</a>
            <a href="">招聘信息</a>
            <a href="">意见反馈</a>
            <a href="">隐私保护</a>
            <a href="">帮助中心</a>
            <a href="">交友须知</a>
            <p>金玉良缘网是一个面向高素质单身人士的专业婚恋服务平台，在国内拥有多家股份公司的雄厚背景。</p>
            <span>CopyRight 2017 蜀ICP备15018437号-1  地址：成都市青羊区西御街西御大厦A座25楼</span>
        </div>
    	<div class="footer2"><img src="/images/xy_53.jpg" alt="网页底部" /></div>
    </div>