<?php
$z[0]=Array("include","",576,613);
$z[0][4]['filename']="header.htm";
$z[1]=Array("list","\r\n            <div class=\"hdong_list\">\r\n            	<div class=\"hdong_list_tit\"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></div>\r\n            	<div class=\"hdong_list_img\"><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" /></a><p>已报名人数：[field:baoming/]人</p></div>\r\n            	<div class=\"hdong_list_bm\">活动时间：[field:shijian function=\"MyDate('Y-m-d H:i',@me)\"/] <a href=\"[field:arcurl/]\" target=\"_blank\">免费报名</a></div>\r\n            </div>\r\n            ",976,1608);
$z[1][4]['flag']="a";
$z[1][4]['pagesize']="20";
$z[1][4]['addfields']="baoming,shijian";
$z[1][4]['channelid']="18";
$z[2]=Array("list","\r\n            <div class=\"hdong_list\">\r\n            	<div class=\"hdong_list_tit\"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></div>\r\n            	<div class=\"hdong_list_img\"><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" /></a><p>已报名人数：[field:baoming/]人</p></div>\r\n            	<div class=\"hdong_list_bm\">活动已结束 <a href=\"[field:arcurl/]\" target=\"_blank\" class=\"bmjz\">报名截止</a></div>\r\n            </div>\r\n            ",1805,2399);
$z[2][4]['flag']="s";
$z[2][4]['pagesize']="20";
$z[2][4]['addfields']="baoming,shijian";
$z[2][4]['channelid']="18";
$z[3]=Array("include","",2489,2533);
$z[3][4]['filename']="huodong_right.htm";
$z[4]=Array("include","",2630,2667);
$z[4][4]['filename']="footer.htm";

?>