<?php
$z[0]=Array("include","",530,567);
$z[0][4]['filename']="header.htm";
$z[1]=Array("field","",748,777);
$z[1][4]['name']="position";
$z[2]=Array("arclist","\r\n                            <li><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:bigimg /]\" alt=\"[field:title/]\" /></a></li>\r\n                            ",1007,1295);
$z[2][4]['titlelen']="100";
$z[2][4]['typeid']="6";
$z[2][4]['row']="5";
$z[2][4]['flag']="f";
$z[2][4]['orderby']="update";
$z[2][4]['addfields']="bigimg";
$z[2][4]['channelid']="1";
$z[3]=Array("field","",1900,1922);
$z[3][4]['name']="typename";
$z[4]=Array("list","\r\n                    \r\n                	<div class=\"newslist_count\">\r\n                    	<a href=\"[field:arcurl/]\" target=\"_blank\">\r\n                        <h2><b>[[field:typename /]]</b> [field:title/]</h2>\r\n                        <div class=\"clear\"></div>\r\n                        <ul>\r\n                        	[field:id function=Getimgs(@me,3,'li')/]\r\n                        </ul>\r\n                        <div class=\"clear\"></div>\r\n                        <div class=\"news_info\">[field:pubdate function=\"GetDateTimeMK(@me)\"/]</div>\r\n                        </a>\r\n                    </div>\r\n                    \r\n                    ",2041,2735);
$z[4][4]['pagesize']="10";
$z[4][4]['orderby']="id";
$z[5]=Array("arclist","\r\n                	<li>\r\n                    	<div class=\"kt_newright2_img\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic /]\" alt=\"[field:title/]\" /></a></div>\r\n                        <div class=\"kt_newright2_title\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n                        <div class=\"kt_newright2_info\">[field:info/]</div>\r\n                    </li>\r\n                    ",3960,4442);
$z[5][4]['titlelen']="100";
$z[5][4]['row']="5";
$z[5][4]['orderby']="click";
$z[5][4]['typeid']="6";
$z[5][4]['subday']="7";
$z[6]=Array("include","",5155,5192);
$z[6][4]['filename']="footer.htm";

?>